# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: python -m pytest
  displayName: 'Run unit tests'

- script: docker build -t rag-app .
  displayName: 'Build Docker image'